### PR TITLE
remove unnecessary unescaping

### PR DESCRIPTION
**Pull request by james-hu**

### CODE REVIEW

**Comment by james-hu** [comment]
@luyilin I found that the unescaping is actually not needed. Also, moving styling to <pre> does not work.

**Comment by james-hu** [comment]
@luyilin Are you happy to have this PR merged?

**Comment by james-hu** [comment]
@luyilin 觉得怎么样啊？

**Comment by luyilin** [comment]
最近有点忙碌，稍等我发一版

**Comment by james-hu** [comment]
> 最近有点忙碌，稍等我发一版

好的

**Comment by luyilin** [comment]
released on v1.0.3

**Pull request merged**
